#############################################################################
# Makefile for building: csg_particules
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  csg_particules.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile csg_particules.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-vectorMatrix \
		sub-image \
		sub-csg \
		sub-Testing \
		sub-InterfaceCSG


sub-vectorMatrix-qmake_all:  FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd vectorMatrix/ && $(MAKE) -f Makefile qmake_all
sub-vectorMatrix: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-vectorMatrix-make_first-ordered: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-vectorMatrix-make_first: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-vectorMatrix-all-ordered: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-vectorMatrix-all: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-vectorMatrix-clean-ordered: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-vectorMatrix-clean: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-vectorMatrix-distclean-ordered: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-vectorMatrix-distclean: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-vectorMatrix-install_subtargets-ordered: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-vectorMatrix-install_subtargets: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-vectorMatrix-uninstall_subtargets-ordered: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-vectorMatrix-uninstall_subtargets: FORCE
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-image-qmake_all: sub-vectorMatrix-qmake_all FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd image/ && $(MAKE) -f Makefile qmake_all
sub-image: FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-image-make_first-ordered: sub-vectorMatrix-make_first-ordered  FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-image-make_first: FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-image-all-ordered: sub-vectorMatrix-all-ordered  FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-image-all: FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-image-clean-ordered: sub-vectorMatrix-clean-ordered  FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-image-clean: FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-image-distclean-ordered: sub-vectorMatrix-distclean-ordered  FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-image-distclean: FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-image-install_subtargets-ordered: sub-vectorMatrix-install_subtargets-ordered  FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-image-install_subtargets: FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-image-uninstall_subtargets-ordered: sub-vectorMatrix-uninstall_subtargets-ordered  FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-image-uninstall_subtargets: FORCE
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-csg-qmake_all: sub-image-qmake_all FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd csg/ && $(MAKE) -f Makefile qmake_all
sub-csg: FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-csg-make_first-ordered: sub-image-make_first-ordered  FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-csg-make_first: FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-csg-all-ordered: sub-image-all-ordered  FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-csg-all: FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-csg-clean-ordered: sub-image-clean-ordered  FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-csg-clean: FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-csg-distclean-ordered: sub-image-distclean-ordered  FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-csg-distclean: FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-csg-install_subtargets-ordered: sub-image-install_subtargets-ordered  FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-csg-install_subtargets: FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-csg-uninstall_subtargets-ordered: sub-image-uninstall_subtargets-ordered  FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-csg-uninstall_subtargets: FORCE
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Testing-qmake_all: sub-csg-qmake_all FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd Testing/ && $(MAKE) -f Makefile qmake_all
sub-Testing: FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-Testing-make_first-ordered: sub-csg-make_first-ordered  FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Testing-make_first: FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Testing-all-ordered: sub-csg-all-ordered  FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Testing-all: FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Testing-clean-ordered: sub-csg-clean-ordered  FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Testing-clean: FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Testing-distclean-ordered: sub-csg-distclean-ordered  FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Testing-distclean: FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Testing-install_subtargets-ordered: sub-csg-install_subtargets-ordered  FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Testing-install_subtargets: FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Testing-uninstall_subtargets-ordered: sub-csg-uninstall_subtargets-ordered  FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Testing-uninstall_subtargets: FORCE
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-InterfaceCSG-qmake_all: sub-Testing-qmake_all FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd InterfaceCSG/ && $(MAKE) -f Makefile qmake_all
sub-InterfaceCSG: FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-InterfaceCSG-make_first-ordered: sub-Testing-make_first-ordered  FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-InterfaceCSG-make_first: FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-InterfaceCSG-all-ordered: sub-Testing-all-ordered  FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-InterfaceCSG-all: FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-InterfaceCSG-clean-ordered: sub-Testing-clean-ordered  FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-InterfaceCSG-clean: FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-InterfaceCSG-distclean-ordered: sub-Testing-distclean-ordered  FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-InterfaceCSG-distclean: FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-InterfaceCSG-install_subtargets-ordered: sub-Testing-install_subtargets-ordered  FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-InterfaceCSG-install_subtargets: FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-InterfaceCSG-uninstall_subtargets-ordered: sub-Testing-uninstall_subtargets-ordered  FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-InterfaceCSG-uninstall_subtargets: FORCE
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: csg_particules.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/declarative_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		csg_particules.pro
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile csg_particules.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/declarative_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
csg_particules.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile csg_particules.pro

qmake_all: sub-vectorMatrix-qmake_all sub-image-qmake_all sub-csg-qmake_all sub-Testing-qmake_all sub-InterfaceCSG-qmake_all FORCE

make_first: sub-vectorMatrix-make_first-ordered sub-image-make_first-ordered sub-csg-make_first-ordered sub-Testing-make_first-ordered sub-InterfaceCSG-make_first-ordered FORCE
all: sub-vectorMatrix-all-ordered sub-image-all-ordered sub-csg-all-ordered sub-Testing-all-ordered sub-InterfaceCSG-all-ordered FORCE
clean: sub-vectorMatrix-clean-ordered sub-image-clean-ordered sub-csg-clean-ordered sub-Testing-clean-ordered sub-InterfaceCSG-clean-ordered FORCE
distclean: sub-vectorMatrix-distclean-ordered sub-image-distclean-ordered sub-csg-distclean-ordered sub-Testing-distclean-ordered sub-InterfaceCSG-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-vectorMatrix-install_subtargets-ordered sub-image-install_subtargets-ordered sub-csg-install_subtargets-ordered sub-Testing-install_subtargets-ordered sub-InterfaceCSG-install_subtargets-ordered FORCE
uninstall_subtargets: sub-vectorMatrix-uninstall_subtargets-ordered sub-image-uninstall_subtargets-ordered sub-csg-uninstall_subtargets-ordered sub-Testing-uninstall_subtargets-ordered sub-InterfaceCSG-uninstall_subtargets-ordered FORCE

sub-vectorMatrix-check_ordered:
	@test -d vectorMatrix/ || mkdir -p vectorMatrix/
	cd vectorMatrix/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/vectorMatrix/vectorMatrix.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-image-check_ordered: sub-vectorMatrix-check_ordered 
	@test -d image/ || mkdir -p image/
	cd image/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/image/image.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-csg-check_ordered: sub-image-check_ordered 
	@test -d csg/ || mkdir -p csg/
	cd csg/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/csg/csg.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-Testing-check_ordered: sub-csg-check_ordered 
	@test -d Testing/ || mkdir -p Testing/
	cd Testing/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/Testing/Testing.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-InterfaceCSG-check_ordered: sub-Testing-check_ordered 
	@test -d InterfaceCSG/ || mkdir -p InterfaceCSG/
	cd InterfaceCSG/ && ( test -e Makefile || $(QMAKE) /adhome/n/nl/nlutz/cpoa_s1/cpoa_m1s1/InterfaceCSG/InterfaceCSG.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-vectorMatrix-check_ordered sub-image-check_ordered sub-csg-check_ordered sub-Testing-check_ordered sub-InterfaceCSG-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

